import { Schema, Column, ColumnType } from '@/types/schema';

const typeToSQL = (type: ColumnType): string => {
  const mapping: Record<ColumnType, string> = {
    uuid: 'UUID',
    serial: 'SERIAL',
    integer: 'INTEGER',
    bigint: 'BIGINT',
    text: 'TEXT',
    varchar: 'VARCHAR(255)',
    boolean: 'BOOLEAN',
    timestamp: 'TIMESTAMP',
    date: 'DATE',
    json: 'JSON',
    jsonb: 'JSONB',
    decimal: 'DECIMAL(10,2)',
    float: 'FLOAT',
  };
  return mapping[type] || 'TEXT';
};

const columnToSQL = (column: Column): string => {
  const parts: string[] = [
    `"${column.name}"`,
    typeToSQL(column.type),
  ];
  
  if (column.isPrimary) {
    parts.push('PRIMARY KEY');
  }
  
  if (!column.isNullable && !column.isPrimary) {
    parts.push('NOT NULL');
  }
  
  if (column.isUnique && !column.isPrimary) {
    parts.push('UNIQUE');
  }
  
  if (column.type === 'uuid' && column.isPrimary) {
    parts.push('DEFAULT gen_random_uuid()');
  }
  
  return parts.join(' ');
};

export const exportToSQL = (schema: Schema): string => {
  const lines: string[] = [];
  
  lines.push('-- Generated by Visual Database Designer');
  lines.push('-- ' + new Date().toISOString());
  lines.push('');
  
  // Create tables
  for (const table of schema.tables) {
    lines.push(`CREATE TABLE "${table.name}" (`);
    
    const columnDefs = table.columns.map((col, idx) => {
      const comma = idx < table.columns.length - 1 ? ',' : '';
      return `  ${columnToSQL(col)}${comma}`;
    });
    
    lines.push(...columnDefs);
    lines.push(');');
    lines.push('');
  }
  
  // Create foreign keys
  for (const rel of schema.relationships) {
    const fromTable = schema.tables.find(t => t.id === rel.fromTableId);
    const toTable = schema.tables.find(t => t.id === rel.toTableId);
    const fromColumn = fromTable?.columns.find(c => c.id === rel.fromColumnId);
    const toColumn = toTable?.columns.find(c => c.id === rel.toColumnId);
    
    if (fromTable && toTable && fromColumn && toColumn) {
      lines.push(`ALTER TABLE "${fromTable.name}"`);
      lines.push(`  ADD CONSTRAINT "fk_${fromTable.name}_${fromColumn.name}"`);
      lines.push(`  FOREIGN KEY ("${fromColumn.name}")`);
      lines.push(`  REFERENCES "${toTable.name}" ("${toColumn.name}");`);
      lines.push('');
    }
  }
  
  return lines.join('\n');
};

export const downloadSQL = (schema: Schema, filename: string = 'schema.sql') => {
  const sql = exportToSQL(schema);
  const blob = new Blob([sql], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};
